apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: metrics-server
  annotations:
    kapp.k14s.io/change-group: "tce-local/metrics-server"
spec:
  packageRef:
    refName: metrics-server.community.tanzu.vmware.com
    versionSelection:
      constraints: ">=0.5.1"
  serviceAccountName: local-core-default-sa
  values:
  - secretRef:
      name: metrics-server-pkg-values
---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-server-pkg-values
  annotations:
    kapp.k14s.io/change-group: "tce-local/metrics-server"
type: Opaque
stringData:
  values.yml: |-
    namespace: metrics-server
